id: IE3EE50DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:17:26+00:00'
last_modified: '2022-06-08T06:18:21.530592+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5872
  title: བསམ་ཡས་རྩོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C54D:
      image_group_id: I1KG5891
      title: ''
      total_pages: 489
      order: 1
      base_file: C54D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
